#!/bin/env php
<?php
$creator_mbox 	= 'admin';
$creator_passwd = 'geheim';
$server_no 	= 0;				// you can leave it at that
$verbose	= true;				// display information (including passwords) and errors?

$new_user_ops	= array(			// see inc/lib/openmailadmin.php::mailbox_create
	'pate'		=> $creator_mbox,
	'canonical'	=> '@example.com',	// mailbox name will be prepended
	'domains'	=> 'example.com',	// or domain key
	'max_alias'	=> 10,
	'max_regexp'	=> 0,
	'quota'		=> 100,			// in MiB
);

//////////////////////////////////////////////////////////////////////////////////
// don't change anything below
//////////////////////////////////////////////////////////////////////////////////

ini_set('log_errors', '0');
ini_set('display_errors', '1');
error_reporting(E_ALL);
$_SERVER['HTTP_ACCEPT_LANGUAGE'] = 'shell';

include('./inc/config.inc.php');
@(include('./inc/config.local.inc.php'))
	or die('You have to create an configuration file, first. Try <a href="setup.php">setup.php</a>.');
include('./inc/translation.inc.php');
include('adodb/adodb.inc.php');
include('./inc/functions.inc.php');

if(!isset($cfg['Servers']['IMAP'][$server_no]['TYPE'])) {
	die('You have forgotten to set TYPEs in the configuration files!');
}

// table names with prefixes
$cfg['tablenames'] = array();
foreach(array('user', 'domains', 'virtual', 'virtual_regexp', 'imap_demo') as $table) {
	$cfg['tablenames'][$table] = $cfg['Servers']['DB'][$server_no]['PREFIX'].$table;
}

// Objects' initialization
$db			= ADONewConnection($cfg['Servers']['DB'][$server_no]['DSN'])
				or die('Cannot connect to database server.');
User::$db		= $db;
User::$tablenames	= $cfg['tablenames'];

// IMAP
$imap = IMAP_get_instance($cfg['Servers']['IMAP'][$server_no],
			$cfg['Servers']['IMAP'][$server_no]['TYPE']);

// include the backend
$oma	= new openmailadmin($db, $cfg['tablenames'], $cfg, $imap);
$oma->authenticated_user	= User::authenticate($creator_mbox, $creator_passwd);
$oma->current_user		= $oma->authenticated_user;
$ErrorHandler	= ErrorHandler::getInstance();

//////////////////////////////////////////////////////////////////////////////////

if($fp = fopen('php://stdin', 'r')) {
	$users_created = array();
	while(!feof($fp)) {
		$line = fgets($fp, 1024);
		$usr = trim($line);
		if($usr != '') {
			$w = $new_user_ops;
			$w['mbox'] = $usr;
			$w['person'] = $usr.' (bulk created)';
			$w['canonical'] = $usr.$w['canonical'];
			echo("Creating mailbox for '".$usr."'... ");

			try {
				if($oma->mailbox_create($usr, $w)) {
					$users_created[] = $usr;
					echo("OK\n");
				} else {
					throw new Exception('mailbox_create returned false');
				}
			} catch (Exception $e) {
				if($verbose) {
					echo("failed: \n".$e->getMessage()."\n");
				} else {
					echo("failed\n");
				}
			}
			if($verbose) {
				echo($ErrorHandler->errors_get());
				echo($ErrorHandler->info_get());
				$ErrorHandler->status_reset();
			}
		}
	}
	fclose($fp);
	// activate users which have been created successfully
	$oma->mailbox_toggle_active($users_created);
}
echo("--\n");

?>